import type { Language } from '@/store';

export type OnboardingCopy = {
  languageTitle: string;
  languageBody: string;
  languageButton: string;
  skip: string;
  next: string;
  setupNow: string;
  setupTitle: string;
  setupBody: string;
  parentLabel: string;
  parentPlaceholder: string;
  permissionsLabel: string;
  locationTitle: string;
  locationBody: string;
  notificationsTitle: string;
  notificationsBody: string;
  finish: string;
  saving: string;
  error: string;
  footer: string;
  slides: Array<{ title: string; body: string }>;
};

const COPY: Record<Language, OnboardingCopy> = {
  en: {
    languageTitle: 'Choose your language',
    languageBody: 'Tutorial, setup, and voice guidance will continue in this language.',
    languageButton: 'Continue',
    skip: 'Skip',
    next: 'Next',
    setupNow: 'Set up now',
    setupTitle: 'Create your family profile',
    setupBody: 'Enter the correct parent and child details you want to see across the app.',
    parentLabel: 'Parent name',
    parentPlaceholder: 'Enter parent name',
    permissionsLabel: 'Optional permissions',
    locationTitle: 'Location',
    locationBody: 'Find nearby vaccination centres faster.',
    notificationsTitle: 'Reminders',
    notificationsBody: 'Get vaccine reminders before the due date.',
    finish: 'Go to app',
    saving: 'Saving your profile...',
    error: 'Setup could not be completed. Please try again.',
    footer: 'Ministry of Health and Family Welfare | Government of India',
    slides: [
      { title: 'Track every vaccine', body: 'Keep every child vaccine update together in one safe place.' },
      { title: 'Know what is due', body: 'See which vaccines are due today, this week, and next.' },
      { title: 'Find help nearby', body: 'Book appointments and nearby centres in your chosen language.' },
    ],
  },
  hi: {
    languageTitle: 'अपनी भाषा चुनें',
    languageBody: 'ट्यूटोरियल, सेटअप और आवाज़ मार्गदर्शन इसी भाषा में आगे चलेगा।',
    languageButton: 'आगे बढ़ें',
    skip: 'छोड़ें',
    next: 'अगला',
    setupNow: 'अभी सेटअप करें',
    setupTitle: 'अपना परिवार प्रोफ़ाइल बनाएँ',
    setupBody: 'ऐप में सही जानकारी दिखाने के लिए माता-पिता और बच्चे की जानकारी भरें।',
    parentLabel: 'माता या पिता का नाम',
    parentPlaceholder: 'माता या पिता का नाम लिखें',
    permissionsLabel: 'वैकल्पिक अनुमतियाँ',
    locationTitle: 'लोकेशन',
    locationBody: 'नज़दीकी टीकाकरण केंद्र जल्दी खोजें।',
    notificationsTitle: 'रिमाइंडर',
    notificationsBody: 'टीके की तारीख़ से पहले याद दिलाने वाली सूचना पाएँ।',
    finish: 'ऐप में जाएँ',
    saving: 'आपकी प्रोफ़ाइल सेव की जा रही है...',
    error: 'सेटअप पूरा नहीं हो सका। कृपया फिर से प्रयास करें।',
    footer: 'स्वास्थ्य एवं परिवार कल्याण मंत्रालय | भारत सरकार',
    slides: [
      { title: 'हर टीके का रिकॉर्ड रखें', body: 'बच्चे के सभी टीकाकरण अपडेट एक सुरक्षित जगह पर रखें।' },
      { title: 'क्या बाकी है तुरंत जानें', body: 'आज, इस हफ्ते और आगे के टीके तुरंत देखें।' },
      { title: 'पास में मदद पाएँ', body: 'अपनी चुनी हुई भाषा में केंद्र खोजें और अपॉइंटमेंट बुक करें।' },
    ],
  },
  mr: {
    languageTitle: 'तुमची भाषा निवडा',
    languageBody: 'ट्युटोरियल, सेटअप आणि आवाज मार्गदर्शन हीच भाषा वापरेल.',
    languageButton: 'पुढे चला',
    skip: 'वगळा',
    next: 'पुढे',
    setupNow: 'आता सेटअप करा',
    setupTitle: 'कुटुंब प्रोफाइल तयार करा',
    setupBody: 'अॅपमध्ये योग्य माहिती दिसण्यासाठी पालक आणि मुलाची माहिती भरा.',
    parentLabel: 'पालकांचे नाव',
    parentPlaceholder: 'पालकांचे नाव टाका',
    permissionsLabel: 'पर्यायी परवानग्या',
    locationTitle: 'लोकेशन',
    locationBody: 'जवळचे लसीकरण केंद्र पटकन शोधा.',
    notificationsTitle: 'स्मरणपत्रे',
    notificationsBody: 'लस देय तारखेआधी स्मरणपत्र मिळवा.',
    finish: 'अॅपमध्ये जा',
    saving: 'तुमची प्रोफाइल सेव होत आहे...',
    error: 'सेटअप पूर्ण झाला नाही. कृपया पुन्हा प्रयत्न करा.',
    footer: 'आरोग्य व कुटुंब कल्याण मंत्रालय | भारत सरकार',
    slides: [
      { title: 'प्रत्येक लसीचा मागोवा घ्या', body: 'मुलाच्या सर्व लसीकरण अपडेट्स एकाच सुरक्षित ठिकाणी ठेवा.' },
      { title: 'काय बाकी आहे ते जाणून घ्या', body: 'आज, या आठवड्यात आणि पुढील लसी पटकन पहा.' },
      { title: 'जवळची मदत मिळवा', body: 'तुमच्या भाषेत केंद्र शोधा आणि अपॉइंटमेंट बुक करा.' },
    ],
  },
  bn: {
    languageTitle: 'আপনার ভাষা বেছে নিন',
    languageBody: 'টিউটোরিয়াল, সেটআপ এবং ভয়েস গাইড এই ভাষাতেই চলবে।',
    languageButton: 'এগিয়ে যান',
    skip: 'এড়িয়ে যান',
    next: 'পরবর্তী',
    setupNow: 'এখন সেটআপ করুন',
    setupTitle: 'আপনার পরিবার প্রোফাইল তৈরি করুন',
    setupBody: 'অ্যাপে সঠিক তথ্য দেখাতে অভিভাবক ও শিশুর তথ্য দিন।',
    parentLabel: 'অভিভাবকের নাম',
    parentPlaceholder: 'অভিভাবকের নাম লিখুন',
    permissionsLabel: 'ঐচ্ছিক অনুমতি',
    locationTitle: 'লোকেশন',
    locationBody: 'কাছের টিকাকরণ কেন্দ্র দ্রুত খুঁজুন।',
    notificationsTitle: 'রিমাইন্ডার',
    notificationsBody: 'টিকার তারিখের আগে মনে করিয়ে দেওয়া নোটিফিকেশন পান।',
    finish: 'অ্যাপে যান',
    saving: 'আপনার প্রোফাইল সেভ করা হচ্ছে...',
    error: 'সেটআপ সম্পূর্ণ হয়নি। অনুগ্রহ করে আবার চেষ্টা করুন।',
    footer: 'স্বাস্থ্য ও পরিবার কল্যাণ মন্ত্রক | ভারত সরকার',
    slides: [
      { title: 'প্রতিটি টিকার হিসাব রাখুন', body: 'শিশুর সব টিকাকরণ আপডেট এক জায়গায় নিরাপদে রাখুন।' },
      { title: 'কী বাকি আছে দেখুন', body: 'আজ, এই সপ্তাহে এবং পরের টিকা দ্রুত দেখুন।' },
      { title: 'কাছেই সাহায্য পান', body: 'আপনার ভাষায় কেন্দ্র খুঁজুন এবং অ্যাপয়েন্টমেন্ট বুক করুন।' },
    ],
  },
  te: {
    languageTitle: 'మీ భాషను ఎంచుకోండి',
    languageBody: 'ట్యుటోరియల్, సెటప్ మరియు వాయిస్ మార్గదర్శనం ఇదే భాషలో కొనసాగుతుంది.',
    languageButton: 'కొనసాగించండి',
    skip: 'దాటవేయండి',
    next: 'తర్వాత',
    setupNow: 'ఇప్పుడే సెటప్ చేయండి',
    setupTitle: 'మీ కుటుంబ ప్రొఫైల్ రూపొందించండి',
    setupBody: 'యాప్ అంతటా సరైన వివరాలు కనిపించేందుకు తల్లిదండ్రి మరియు పిల్లల వివరాలు నమోదు చేయండి.',
    parentLabel: 'తల్లిదండ్రి పేరు',
    parentPlaceholder: 'తల్లిదండ్రి పేరు నమోదు చేయండి',
    permissionsLabel: 'ఐచ్చిక అనుమతులు',
    locationTitle: 'లోకేషన్',
    locationBody: 'దగ్గరలోని టీకా కేంద్రాలను త్వరగా కనుగొనండి.',
    notificationsTitle: 'రిమైండర్లు',
    notificationsBody: 'టీకా తేదీకి ముందే గుర్తు చేసే నోటిఫికేషన్ పొందండి.',
    finish: 'యాప్‌లోకి వెళ్లండి',
    saving: 'మీ ప్రొఫైల్ సేవ్ అవుతోంది...',
    error: 'సెటప్ పూర్తి కాలేదు. దయచేసి మళ్లీ ప్రయత్నించండి.',
    footer: 'ఆరోగ్య మరియు కుటుంబ సంక్షేమ మంత్రిత్వ శాఖ | భారత ప్రభుత్వం',
    slides: [
      { title: 'ప్రతి టీకాను గమనించండి', body: 'పిల్లల అన్ని టీకా వివరాలను ఒకే సురక్షిత స్థలంలో ఉంచండి.' },
      { title: 'ఏవి మిగిలి ఉన్నాయో తెలుసుకోండి', body: 'ఈ రోజు, ఈ వారం, తర్వాత వచ్చే టీకాలను వెంటనే చూడండి.' },
      { title: 'దగ్గర్లో సహాయం పొందండి', body: 'మీ భాషలో కేంద్రాలను కనుగొని అపాయింట్మెంట్ బుక్ చేయండి.' },
    ],
  },
  ta: {
    languageTitle: 'உங்கள் மொழியை தேர்வு செய்யுங்கள்',
    languageBody: 'டுடோரியல், அமைப்பு மற்றும் குரல் வழிகாட்டுதல் இந்த மொழியிலேயே தொடரும்.',
    languageButton: 'தொடரவும்',
    skip: 'தவிர்க்கவும்',
    next: 'அடுத்து',
    setupNow: 'இப்போது அமைக்கவும்',
    setupTitle: 'உங்கள் குடும்ப சுயவிவரத்தை உருவாக்குங்கள்',
    setupBody: 'பயன்பாட்டில் சரியான தகவல் காண பெற்றோர் மற்றும் குழந்தை விவரங்களை உள்ளிடுங்கள்.',
    parentLabel: 'பெற்றோரின் பெயர்',
    parentPlaceholder: 'பெற்றோரின் பெயரை உள்ளிடுங்கள்',
    permissionsLabel: 'விருப்ப அனுமதிகள்',
    locationTitle: 'இடம்',
    locationBody: 'அருகிலுள்ள தடுப்பூசி மையங்களை விரைவாக கண்டுபிடிக்கவும்.',
    notificationsTitle: 'நினைவூட்டல்கள்',
    notificationsBody: 'தடுப்பூசி தேதிக்கு முன் நினைவூட்டல் அறிவிப்புகளை பெறுங்கள்.',
    finish: 'பயன்பாட்டுக்கு செல்லவும்',
    saving: 'உங்கள் சுயவிவரம் சேமிக்கப்படுகிறது...',
    error: 'அமைப்பு முடிக்கப்படவில்லை. தயவுசெய்து மீண்டும் முயற்சிக்கவும்.',
    footer: 'சுகாதார மற்றும் குடும்ப நல அமைச்சகம் | இந்திய அரசு',
    slides: [
      { title: 'ஒவ்வொரு தடுப்பூசியையும் கண்காணிக்கவும்', body: 'குழந்தையின் அனைத்து தடுப்பூசி தகவல்களையும் ஒரு பாதுகாப்பான இடத்தில் வைத்திருங்கள்.' },
      { title: 'எது நிலுவையில் உள்ளது பாருங்கள்', body: 'இன்று, இந்த வாரம் மற்றும் அடுத்த தடுப்பூசிகளை உடனே பார்க்கலாம்.' },
      { title: 'அருகில் உதவி பெறுங்கள்', body: 'உங்கள் மொழியில் மையங்களை கண்டுபிடித்து நேரம் பதிவு செய்யுங்கள்.' },
    ],
  },
  kn: {
    languageTitle: 'ನಿಮ್ಮ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    languageBody: 'ಪಾಠ ಪರಿಚಯ, ಸೆಟಪ್ ಮತ್ತು ಧ್ವನಿ ಮಾರ್ಗದರ್ಶನ ಇದೇ ಭಾಷೆಯಲ್ಲಿ ಮುಂದುವರಿಯುತ್ತದೆ.',
    languageButton: 'ಮುಂದುವರಿಸಿ',
    skip: 'ಬಿಟ್ಟುಬಿಡಿ',
    next: 'ಮುಂದೆ',
    setupNow: 'ಈಗ ಸೆಟಪ್ ಮಾಡಿ',
    setupTitle: 'ನಿಮ್ಮ ಕುಟುಂಬ ಪ್ರೊಫೈಲ್ ರಚಿಸಿ',
    setupBody: 'ಆಪ್‌ದಲ್ಲಿ ಸರಿಯಾದ ಮಾಹಿತಿ ಕಾಣಲು ಪೋಷಕ ಮತ್ತು ಮಗುವಿನ ವಿವರಗಳನ್ನು ನಮೂದಿಸಿ.',
    parentLabel: 'ಪೋಷಕರ ಹೆಸರು',
    parentPlaceholder: 'ಪೋಷಕರ ಹೆಸರನ್ನು ನಮೂದಿಸಿ',
    permissionsLabel: 'ಐಚ್ಛಿಕ ಅನುಮತಿಗಳು',
    locationTitle: 'ಸ್ಥಳ',
    locationBody: 'ಹತ್ತಿರದ ಲಸಿಕಾ ಕೇಂದ್ರಗಳನ್ನು ಬೇಗ ಹುಡುಕಿ.',
    notificationsTitle: 'ಜ್ಞಾಪನೆಗಳು',
    notificationsBody: 'ಲಸಿಕೆ ದಿನಾಂಕಕ್ಕೂ ಮೊದಲು ನೆನಪಿಸುವ ಸೂಚನೆಗಳನ್ನು ಪಡೆಯಿರಿ.',
    finish: 'ಆಪ್‌ಗೆ ಹೋಗಿ',
    saving: 'ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ಉಳಿಸಲಾಗುತ್ತಿದೆ...',
    error: 'ಸೆಟಪ್ ಪೂರ್ಣಗೊಳಿಸಲಾಗಲಿಲ್ಲ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    footer: 'ಆರೋಗ್ಯ ಮತ್ತು ಕುಟುಂಬ ಕಲ್ಯಾಣ ಸಚಿವಾಲಯ | ಭಾರತ ಸರ್ಕಾರ',
    slides: [
      { title: 'ಪ್ರತಿ ಲಸಿಕೆಯನ್ನು ಗಮನದಲ್ಲಿಡಿ', body: 'ಮಗುವಿನ ಎಲ್ಲಾ ಲಸಿಕಾ ವಿವರಗಳನ್ನು ಒಂದು ಸುರಕ್ಷಿತ ಸ್ಥಳದಲ್ಲಿ ಇಡಿ.' },
      { title: 'ಏನು ಬಾಕಿಯಿದೆ ನೋಡಿ', body: 'ಇಂದು, ಈ ವಾರ ಮತ್ತು ಮುಂದಿನ ಲಸಿಕೆಗಳನ್ನು ತಕ್ಷಣ ನೋಡಿ.' },
      { title: 'ಹತ್ತಿರದ ಸಹಾಯ ಪಡೆಯಿರಿ', body: 'ನಿಮ್ಮ ಭಾಷೆಯಲ್ಲಿ ಕೇಂದ್ರಗಳನ್ನು ಹುಡುಕಿ ಮತ್ತು ಬುಕ್ಕಿಂಗ್ ಮಾಡಿ.' },
    ],
  },
  gu: {
    languageTitle: 'તમારી ભાષા પસંદ કરો',
    languageBody: 'ટ્યુટોરિયલ, સેટઅપ અને અવાજ માર્ગદર્શન આ જ ભાષામાં ચાલુ રહેશે.',
    languageButton: 'આગળ વધો',
    skip: 'છોડો',
    next: 'આગળ',
    setupNow: 'હવે સેટઅપ કરો',
    setupTitle: 'તમારો પરિવાર પ્રોફાઇલ બનાવો',
    setupBody: 'એપમાં સાચી માહિતી જોવા માટે માતા-પિતા અને બાળકની માહિતી ભરો.',
    parentLabel: 'માતા અથવા પિતાનું નામ',
    parentPlaceholder: 'માતા અથવા પિતાનું નામ લખો',
    permissionsLabel: 'વૈકલ્પિક પરવાનગીઓ',
    locationTitle: 'લોકેશન',
    locationBody: 'નજીકના રસીકરણ કેન્દ્રો ઝડપથી શોધો.',
    notificationsTitle: 'રીમાઇન્ડર',
    notificationsBody: 'રસીની તારીખ પહેલાં યાદ અપાવતી સૂચનાઓ મેળવો.',
    finish: 'એપમાં જાઓ',
    saving: 'તમારી પ્રોફાઇલ સેવ થઈ રહી છે...',
    error: 'સેટઅપ પૂર્ણ થઈ શક્યું નથી. કૃપા કરીને ફરી પ્રયાસ કરો.',
    footer: 'આરોગ્ય અને પરિવાર કલ્યાણ મંત્રાલય | ભારત સરકાર',
    slides: [
      { title: 'દરેક રસીનો હિસાબ રાખો', body: 'બાળકની તમામ રસીની માહિતી એક સુરક્ષિત જગ્યાએ રાખો.' },
      { title: 'શું બાકી છે જુઓ', body: 'આજે, આ અઠવાડિયે અને આગળની રસી તરત જુઓ.' },
      { title: 'નજીક મદદ મેળવો', body: 'તમારી ભાષામાં કેન્દ્ર શોધો અને સમય બુક કરો.' },
    ],
  },
  ml: {
    languageTitle: 'നിങ്ങളുടെ ഭാഷ തിരഞ്ഞെടുക്കുക',
    languageBody: 'ട്യൂട്ടോറിയൽ, സെറ്റപ്പ്, ശബ്ദ മാർഗനിർദ്ദേശം ഇതേ ഭാഷയിൽ തുടരും.',
    languageButton: 'തുടരുക',
    skip: 'ഒഴിവാക്കുക',
    next: 'അടുത്തത്',
    setupNow: 'ഇപ്പോൾ സെറ്റപ്പ് ചെയ്യുക',
    setupTitle: 'നിങ്ങളുടെ കുടുംബ പ്രൊഫൈൽ സൃഷ്ടിക്കൂ',
    setupBody: 'ആപ്പിൽ ശരിയായ വിവരങ്ങൾ കാണാൻ മാതാപിതാവിന്റെയും കുട്ടിയുടെയും വിവരങ്ങൾ നൽകുക.',
    parentLabel: 'മാതാപിതാവിന്റെ പേര്',
    parentPlaceholder: 'മാതാപിതാവിന്റെ പേര് നൽകുക',
    permissionsLabel: 'ഐച്ഛിക അനുമതികൾ',
    locationTitle: 'ലൊക്കേഷൻ',
    locationBody: 'അടുത്തുള്ള വാക്സിനേഷൻ കേന്ദ്രങ്ങൾ വേഗത്തിൽ കണ്ടെത്തൂ.',
    notificationsTitle: 'ഓർമ്മപ്പെടുത്തലുകൾ',
    notificationsBody: 'വാക്സിൻ തീയതിക്ക് മുമ്പ് ഓർമ്മപ്പെടുത്തൽ അറിയിപ്പുകൾ നേടൂ.',
    finish: 'ആപ്പിലേക്ക് പോകുക',
    saving: 'നിങ്ങളുടെ പ്രൊഫൈൽ സേവ് ചെയ്യുന്നു...',
    error: 'സെറ്റപ്പ് പൂർത്തിയാക്കാനായില്ല. ദയവായി വീണ്ടും ശ്രമിക്കുക.',
    footer: 'ആരോഗ്യവും കുടുംബക്ഷേമവും മന്ത്രാലയം | ഇന്ത്യ സർക്കാർ',
    slides: [
      { title: 'ഓരോ വാക്സിനും ശ്രദ്ധിക്കുക', body: 'കുട്ടിയുടെ എല്ലാ വാക്സിൻ വിവരങ്ങളും ഒരു സുരക്ഷിത സ്ഥലത്ത് സൂക്ഷിക്കുക.' },
      { title: 'എന്താണ് ബാക്കി എന്ന് അറിയുക', body: 'ഇന്ന്, ഈ ആഴ്ച, അടുത്തത് വരാനുള്ള വാക്സിനുകൾ ഉടൻ കാണുക.' },
      { title: 'അടുത്ത സഹായം നേടുക', body: 'നിങ്ങളുടെ ഭാഷയിൽ കേന്ദ്രങ്ങൾ കണ്ടെത്തി ബുക്കിംഗ് ചെയ്യൂ.' },
    ],
  },
  pa: {
    languageTitle: 'ਆਪਣੀ ਭਾਸ਼ਾ ਚੁਣੋ',
    languageBody: 'ਟਿਊਟੋਰਿਅਲ, ਸੈਟਅਪ ਅਤੇ ਆਵਾਜ਼ ਮਾਰਗਦਰਸ਼ਨ ਇਸੇ ਭਾਸ਼ਾ ਵਿੱਚ ਚੱਲੇਗਾ।',
    languageButton: 'ਅੱਗੇ ਵਧੋ',
    skip: 'ਛੱਡੋ',
    next: 'ਅੱਗੇ',
    setupNow: 'ਹੁਣ ਸੈਟਅਪ ਕਰੋ',
    setupTitle: 'ਆਪਣੀ ਪਰਿਵਾਰ ਪ੍ਰੋਫ਼ਾਈਲ ਬਣਾਓ',
    setupBody: 'ਐਪ ਵਿੱਚ ਸਹੀ ਜਾਣਕਾਰੀ ਵੇਖਣ ਲਈ ਮਾਤਾ-ਪਿਤਾ ਅਤੇ ਬੱਚੇ ਦੀ ਜਾਣਕਾਰੀ ਭਰੋ।',
    parentLabel: 'ਮਾਤਾ ਜਾਂ ਪਿਤਾ ਦਾ ਨਾਮ',
    parentPlaceholder: 'ਮਾਤਾ ਜਾਂ ਪਿਤਾ ਦਾ ਨਾਮ ਲਿਖੋ',
    permissionsLabel: 'ਵਿਕਲਪਿਕ ਇਜਾਜ਼ਤਾਂ',
    locationTitle: 'ਲੋਕੇਸ਼ਨ',
    locationBody: 'ਨੇੜਲੇ ਟੀਕਾਕਰਨ ਕੇਂਦਰ ਜਲਦੀ ਲੱਭੋ।',
    notificationsTitle: 'ਯਾਦ ਦਿਵਾਉਣੀਆਂ',
    notificationsBody: 'ਟੀਕੇ ਦੀ ਮਿਤੀ ਤੋਂ ਪਹਿਲਾਂ ਯਾਦ ਦਿਵਾਉਣੀ ਸੁਚਨਾ ਪਾਓ।',
    finish: 'ਐਪ ਵਿੱਚ ਜਾਓ',
    saving: 'ਤੁਹਾਡੀ ਪ੍ਰੋਫ਼ਾਈਲ ਸੇਵ ਹੋ ਰਹੀ ਹੈ...',
    error: 'ਸੈਟਅਪ ਪੂਰਾ ਨਹੀਂ ਹੋ ਸਕਿਆ। ਕਿਰਪਾ ਕਰਕੇ ਫਿਰ ਕੋਸ਼ਿਸ਼ ਕਰੋ।',
    footer: 'ਸਿਹਤ ਅਤੇ ਪਰਿਵਾਰ ਕਲਿਆਣ ਮੰਤਰਾਲਾ | ਭਾਰਤ ਸਰਕਾਰ',
    slides: [
      { title: 'ਹਰ ਟੀਕੇ ਦਾ ਰਿਕਾਰਡ ਰੱਖੋ', body: 'ਬੱਚੇ ਦੇ ਸਾਰੇ ਟੀਕਾਕਰਨ ਅੱਪਡੇਟ ਇੱਕ ਸੁਰੱਖਿਅਤ ਥਾਂ ਤੇ ਰੱਖੋ।' },
      { title: 'ਕੀ ਬਾਕੀ ਹੈ ਵੇਖੋ', body: 'ਅੱਜ, ਇਸ ਹਫ਼ਤੇ ਅਤੇ ਅੱਗੇ ਦੇ ਟੀਕੇ ਤੁਰੰਤ ਵੇਖੋ।' },
      { title: 'ਨੇੜੇ ਮਦਦ ਪਾਓ', body: 'ਆਪਣੀ ਭਾਸ਼ਾ ਵਿੱਚ ਕੇਂਦਰ ਲੱਭੋ ਅਤੇ ਸਮਾਂ ਬੁੱਕ ਕਰੋ।' },
    ],
  },
  or: {
    languageTitle: 'ଆପଣଙ୍କ ଭାଷା ବାଛନ୍ତୁ',
    languageBody: 'ଟ୍ୟୁଟୋରିଆଲ, ସେଟଅପ ଏବଂ ଶବ୍ଦ ମାର୍ଗଦର୍ଶନ ଏହି ଭାଷାରେ ଚାଲିବ।',
    languageButton: 'ଆଗକୁ ବଢନ୍ତୁ',
    skip: 'ଏଡ଼ାନ୍ତୁ',
    next: 'ପରବର୍ତ୍ତୀ',
    setupNow: 'ଏବେ ସେଟଅପ କରନ୍ତୁ',
    setupTitle: 'ଆପଣଙ୍କ ପରିବାର ପ୍ରୋଫାଇଲ ତିଆରି କରନ୍ତୁ',
    setupBody: 'ଆପ୍‌ରେ ଠିକ୍ ତଥ୍ୟ ଦେଖିବାକୁ ଅଭିଭାବକ ଏବଂ ଶିଶୁର ତଥ୍ୟ ଭରନ୍ତୁ।',
    parentLabel: 'ଅଭିଭାବକଙ୍କ ନାମ',
    parentPlaceholder: 'ଅଭିଭାବକଙ୍କ ନାମ ଲେଖନ୍ତୁ',
    permissionsLabel: 'ଇଚ୍ଛାନୁସାର ଅନୁମତି',
    locationTitle: 'ଲୋକେସନ',
    locationBody: 'ନିକଟସ୍ଥ ଟିକାକରଣ କେନ୍ଦ୍ର ଶୀଘ୍ର ଖୋଜନ୍ତୁ।',
    notificationsTitle: 'ସ୍ମରଣ',
    notificationsBody: 'ଟିକା ତାରିଖ ପୂର୍ବରୁ ସ୍ମରଣ ସୂଚନା ପାଆନ୍ତୁ।',
    finish: 'ଆପ୍‌କୁ ଯାଆନ୍ତୁ',
    saving: 'ଆପଣଙ୍କ ପ୍ରୋଫାଇଲ ସେଭ ହେଉଛି...',
    error: 'ସେଟଅପ ସମ୍ପୂର୍ଣ୍ଣ ହୋଇନି। ଦୟାକରି ପୁଣି ଚେଷ୍ଟା କରନ୍ତୁ।',
    footer: 'ସ୍ୱାସ୍ଥ୍ୟ ଏବଂ ପରିବାର କଲ୍ୟାଣ ମନ୍ତ୍ରାଳୟ | ଭାରତ ସରକାର',
    slides: [
      { title: 'ପ୍ରତ୍ୟେକ ଟିକାକୁ ନଜରରେ ରଖନ୍ତୁ', body: 'ଶିଶୁର ସମସ୍ତ ଟିକା ତଥ୍ୟକୁ ଏକ ସୁରକ୍ଷିତ ସ୍ଥାନରେ ରଖନ୍ତୁ।' },
      { title: 'କଣ ବାକି ଅଛି ଦେଖନ୍ତୁ', body: 'ଆଜି, ଏହି ସପ୍ତାହ ଓ ପରବର୍ତ୍ତୀ ଟିକା ତୁରନ୍ତ ଦେଖନ୍ତୁ।' },
      { title: 'ନିକଟରେ ସହାୟତା ପାଆନ୍ତୁ', body: 'ଆପଣଙ୍କ ଭାଷାରେ କେନ୍ଦ୍ର ଖୋଜନ୍ତୁ ଏବଂ ବୁକ କରନ୍ତୁ।' },
    ],
  },
  as: {
    languageTitle: 'আপোনাৰ ভাষা বাচনি কৰক',
    languageBody: 'টিউটোৰিয়েল, ছেটআপ আৰু ভয়চ গাইড এই ভাষাতেই চলিব।',
    languageButton: 'আগবাঢ়ক',
    skip: 'এৰি দিয়ক',
    next: 'পৰৱৰ্তী',
    setupNow: 'এতিয়াই ছেটআপ কৰক',
    setupTitle: 'আপোনাৰ পৰিয়ালৰ প্ৰফাইল তৈয়াৰ কৰক',
    setupBody: 'এপত সঠিক তথ্য দেখুৱাবলৈ অভিভাৱক আৰু শিশুৰ তথ্য ভৰ্তি কৰক।',
    parentLabel: 'অভিভাৱকৰ নাম',
    parentPlaceholder: 'অভিভাৱকৰ নাম লিখক',
    permissionsLabel: 'ঐচ্ছিক অনুমতি',
    locationTitle: 'লোকেচন',
    locationBody: 'ওচৰৰ টীকাকৰণ কেন্দ্ৰ সোনকালে বিচাৰি উলিয়াওক।',
    notificationsTitle: 'স্মৰণ',
    notificationsBody: 'টীকাৰ তাৰিখৰ আগতেই স্মৰণ কৰোৱা জাননী পাওক।',
    finish: 'এপলৈ যাওক',
    saving: 'আপোনাৰ প্ৰফাইল ছেভ কৰা হৈছে...',
    error: 'ছেটআপ সম্পূৰ্ণ নহ’ল। অনুগ্ৰহ কৰি পুনৰ চেষ্টা কৰক।',
    footer: 'স্বাস্থ্য আৰু পৰিয়াল কল্যাণ মন্ত্ৰালয় | ভাৰত চৰকাৰ',
    slides: [
      { title: 'প্ৰতিটো টীকাৰ খবৰ ৰাখক', body: 'শিশুৰ সকলো টীকাকৰণ আপডেট এক সুৰক্ষিত ঠাইত ৰাখক।' },
      { title: 'কি বাকী আছে চাওক', body: 'আজিৰ, এই সপ্তাহৰ আৰু আগন্তুক টীকা তৎক্ষণাত চাওক।' },
      { title: 'ওচৰত সহায় পাওক', body: 'আপোনাৰ ভাষাত কেন্দ্ৰ বিচাৰি সময় বুকিং কৰক।' },
    ],
  },
};

export function getOnboardingCopy(language: Language): OnboardingCopy {
  return COPY[language] ?? COPY.en;
}
